import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { About, Contact, Home, Values } from '../components/index';

export default function Landing() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Adept Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Home />
        <About />
        <Values />
        <Contact />
      </main>

      <footer className={styles.footer}>
        <a href="https://alexreyne.me" target="_blank" rel="noopener noreferrer">
          Designed and developed by
          <span className={styles.logo}>
            <Image src="/alex-reyne-logo.png" alt="Alex Reyne Logo" height={35} width={44} />
          </span>
          Alex Reyne
        </a>
      </footer>
    </div>
  );
}
